spring.datasource.url=jdbc:postgresql://localhost:5432/med_docs
spring.datasource.username=postgres
spring.datasource.password=postgre

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.storage.local-root=./uploads
